<?php

/**
 * @file
 * Provides custom functionality for the Resume module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function resume_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.employee':
      return '<h3>' . t('About') . '</h3>' . '<p>' . t('Provides resume management functionality.') . '</p>';

    default:
  }
}

/**
 * Implements hook_theme().
 */
function resume_theme($existing, $type, $theme, $path) {
  return [
    'resumelist' => [
      'variables' => [
        'title' => NULL,
        'details' => NULL,
        'form' => NULL,
      ],
      'template' => 'resumelist',
    ],
  ];
}
